spring:
  datasource:
    url: jdbc:mysql://xxx:3306/jiandan_house?characterEncoding=utf-8&useSSL=false
    username:
    password: @
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update